# Generated by Django 3.2 on 2024-11-15 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('idcargo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_cargo', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'cargo',
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Carrito',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('texto_footer', models.TextField(blank=True, null=True)),
                ('logo', models.BinaryField(blank=True, null=True)),
                ('logo1', models.BinaryField(blank=True, null=True)),
                ('banner', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('cedula', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('edad', models.CharField(blank=True, max_length=50, null=True)),
                ('rol', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='Tbcategorias',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'tbcategorias',
            },
        ),
        migrations.CreateModel(
            name='Tbclientes',
            fields=[
                ('nid_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=30)),
                ('nro_tel', models.CharField(max_length=20)),
                ('movil', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('cedula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appVeterinaria.persona')),
            ],
            options={
                'db_table': 'tbclientes',
            },
        ),
        migrations.CreateModel(
            name='Tbproducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=60)),
                ('vcompra', models.IntegerField()),
                ('vventa', models.IntegerField()),
                ('stock', models.FloatField()),
                ('idCategoria', models.IntegerField()),
            ],
            options={
                'db_table': 'tbproducto',
            },
        ),
        migrations.CreateModel(
            name='TbProveedor',
            fields=[
                ('nid_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=60)),
                ('nro_tel', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
            ],
            options={
                'db_table': 'tbProveedor',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cedula', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('contraseña', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('cliente', 'Cliente'), ('administrador', 'Administrador')], max_length=20)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='TbEncabFacVta',
            fields=[
                ('id_fact', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField(blank=True, null=True)),
                ('nid_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appVeterinaria.tbclientes')),
            ],
            options={
                'db_table': 'tbEncabFacVta',
            },
        ),
        migrations.CreateModel(
            name='TbcomprasEncab',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_compra', models.DateField()),
                ('nid_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appVeterinaria.tbproveedor')),
            ],
            options={
                'db_table': 'tbcomprasEncab',
            },
        ),
        migrations.CreateModel(
            name='TbAlertaStock',
            fields=[
                ('id_alerta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_alerta', models.DateField()),
                ('stock_actual', models.FloatField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appVeterinaria.tbproducto')),
            ],
            options={
                'db_table': 'tbAlertaStock',
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('metodo_pago', models.CharField(blank=True, max_length=30, null=True)),
                ('monto', models.FloatField()),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('id_fact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appVeterinaria.tbencabfacvta')),
            ],
            options={
                'db_table': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id_orden', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_orden', models.DateField(blank=True, null=True)),
                ('id_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appVeterinaria.tbcomprasencab')),
            ],
            options={
                'db_table': 'OrdenCompra',
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('edad', models.CharField(blank=True, max_length=50, null=True)),
                ('especie', models.CharField(blank=True, max_length=40, null=True)),
                ('color', models.CharField(blank=True, max_length=40, null=True)),
                ('tamaño', models.FloatField()),
                ('peso', models.FloatField()),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appVeterinaria.persona')),
            ],
            options={
                'db_table': 'mascota',
            },
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('motivo_consulta', models.CharField(max_length=200)),
                ('sistematologia', models.CharField(max_length=100)),
                ('diagnostico', models.CharField(max_length=200)),
                ('procedimiento', models.CharField(max_length=500)),
                ('medicamento', models.CharField(max_length=30)),
                ('dosis', models.CharField(max_length=40)),
                ('id_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appVeterinaria.mascota')),
                ('id_persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appVeterinaria.persona')),
            ],
            options={
                'db_table': 'historia_clinica',
            },
        ),
        migrations.CreateModel(
            name='DetalleCarrito',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('id_carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appVeterinaria.carrito')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appVeterinaria.tbproducto')),
            ],
            options={
                'db_table': 'DetalleCarrito',
            },
        ),
        migrations.AddField(
            model_name='carrito',
            name='nid_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appVeterinaria.tbclientes'),
        ),
        migrations.CreateModel(
            name='TbDetFactVta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val_venta', models.FloatField()),
                ('cant', models.IntegerField()),
                ('id_fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appVeterinaria.tbencabfacvta')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appVeterinaria.tbproducto')),
            ],
            options={
                'db_table': 'tbDetFactVta',
                'unique_together': {('id_fact', 'id_producto')},
            },
        ),
        migrations.CreateModel(
            name='TbComprasDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val_compra', models.FloatField()),
                ('cant', models.IntegerField()),
                ('id_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appVeterinaria.tbcomprasencab')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appVeterinaria.tbproducto')),
            ],
            options={
                'db_table': 'tbComprasDetalle',
                'unique_together': {('id_compra', 'id_producto')},
            },
        ),
    ]
