# Generated by Django 3.2 on 2024-11-15 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='configuracionempresa',
            table='Configuracionempresa',
        ),
    ]
