# Generated by Django 3.2 on 2024-11-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0002_alter_configuracionempresa_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.BinaryField(blank=True, null=True)),
                ('banner1', models.BinaryField(blank=True, null=True)),
                ('banner2', models.BinaryField(blank=True, null=True)),
                ('banner3', models.BinaryField(blank=True, null=True)),
                ('banner4', models.BinaryField(blank=True, null=True)),
                ('banner5', models.BinaryField(blank=True, null=True)),
                ('banner6', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'db_table': 'banners',
            },
        ),
    ]
