# Generated by Django 3.2 on 2024-11-17 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0004_auto_20241116_1553'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='tbproducto',
            name='idCategoria',
        ),
        migrations.AddField(
            model_name='persona',
            name='contraseña',
            field=models.CharField(default='123', max_length=255),
        ),
        migrations.AddField(
            model_name='tbproducto',
            name='id_categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appVeterinaria.tbcategorias'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbproducto',
            name='imagen',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='descripcion_cargo',
            field=models.CharField(default='Sin descripción', max_length=60),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='fecha_creacion',
            field=models.DateField(blank=True, default='2000-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='detallecarrito',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='diagnostico',
            field=models.CharField(default='Sin diagnóstico', max_length=200),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='dosis',
            field=models.CharField(default='Sin dosis', max_length=40),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='medicamento',
            field=models.CharField(default='Sin medicamento', max_length=30),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='motivo_consulta',
            field=models.CharField(default='Sin motivo', max_length=200),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='procedimiento',
            field=models.CharField(default='Sin procedimiento', max_length=500),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='sistematologia',
            field=models.CharField(default='Sin datos', max_length=100),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='color',
            field=models.CharField(blank=True, default='Desconocido', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='edad',
            field=models.CharField(blank=True, default='Desconocida', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='especie',
            field=models.CharField(blank=True, default='Desconocida', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='peso',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tamaño',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(blank=True, default='Pendiente', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='fecha_orden',
            field=models.DateField(blank=True, default='2000-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='fecha_pago',
            field=models.DateField(blank=True, default='2000-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='metodo_pago',
            field=models.CharField(blank=True, default='Efectivo', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='monto',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('administrador', 'Administrador')], default='cliente', max_length=20),
        ),
        migrations.AlterField(
            model_name='tbalertastock',
            name='fecha_alerta',
            field=models.DateField(blank=True, default='2000-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='tbalertastock',
            name='stock_actual',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='tbcategorias',
            name='descripcion',
            field=models.CharField(default='Sin descripción', max_length=60),
        ),
        migrations.AlterField(
            model_name='tbclientes',
            name='direccion',
            field=models.CharField(default='Sin dirección', max_length=100),
        ),
        migrations.AlterField(
            model_name='tbclientes',
            name='email',
            field=models.EmailField(default='email@ejemplo.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='tbclientes',
            name='movil',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='tbclientes',
            name='nro_tel',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='tbcomprasdetalle',
            name='cant',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tbcomprasdetalle',
            name='val_compra',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='tbcomprasencab',
            name='fecha_compra',
            field=models.DateField(blank=True, default='2000-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='tbproducto',
            name='descripcion',
            field=models.CharField(default='Sin descripción', max_length=100),
        ),
        migrations.AlterField(
            model_name='tbproducto',
            name='nombre',
            field=models.CharField(default='Producto sin nombre', max_length=50),
        ),
        migrations.AlterField(
            model_name='tbproducto',
            name='stock',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='tbproducto',
            name='vcompra',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tbproducto',
            name='vventa',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tbproveedor',
            name='descripcion',
            field=models.CharField(default='Sin descripción', max_length=100),
        ),
        migrations.AlterField(
            model_name='tbproveedor',
            name='direccion',
            field=models.CharField(default='Sin dirección', max_length=100),
        ),
        migrations.AlterField(
            model_name='tbproveedor',
            name='email',
            field=models.EmailField(default='email@ejemplo.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='tbproveedor',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=60),
        ),
        migrations.AlterField(
            model_name='tbproveedor',
            name='nro_tel',
            field=models.CharField(default='0000000000', max_length=20),
        ),
    ]
