# Generated by Django 3.2 on 2024-11-20 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0006_auto_20241120_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionempresa',
            name='banner6',
        ),
    ]
