# Generated by Django 3.2 on 2024-11-23 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0007_remove_configuracionempresa_banner6'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbcategorias',
            old_name='id_categoria',
            new_name='idCategoria',
        ),
        migrations.RemoveField(
            model_name='tbproducto',
            name='id_categoria',
        ),
        migrations.AddField(
            model_name='tbproducto',
            name='idCategoria',
            field=models.ForeignKey(db_column='idCategoria', default=1, on_delete=django.db.models.deletion.CASCADE, to='appVeterinaria.tbcategorias'),
            preserve_default=False,
        ),
    ]
