# Generated by Django 3.2 on 2024-11-27 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0010_auto_20241127_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='nroTel',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='mascota',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=50),
        ),
        migrations.AlterField(
            model_name='cita',
            name='cedula',
            field=models.ForeignKey(db_column='cedula', on_delete=django.db.models.deletion.CASCADE, to='appVeterinaria.persona'),
        ),
    ]
