# Generated by Django 3.2 on 2024-11-27 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0011_auto_20241127_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appVeterinaria.persona'),
        ),
    ]
