# Generated by Django 3.2 on 2024-11-28 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0012_alter_cita_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='mascota',
            field=models.ForeignKey(blank=True, db_column='id_mascota', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appVeterinaria.mascota'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='nroTel',
            field=models.CharField(max_length=20),
        ),
    ]
