# Generated by Django 3.2 on 2024-11-30 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0013_auto_20241127_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbdetfactvta',
            old_name='id_fact',
            new_name='idFact',
        ),
        migrations.RenameField(
            model_name='tbdetfactvta',
            old_name='id_producto',
            new_name='idProducto',
        ),
        migrations.RenameField(
            model_name='tbdetfactvta',
            old_name='val_venta',
            new_name='valVenta',
        ),
        migrations.RenameField(
            model_name='tbencabfacvta',
            old_name='fecha_venta',
            new_name='fechaVenta',
        ),
        migrations.RenameField(
            model_name='tbencabfacvta',
            old_name='id_fact',
            new_name='idFact',
        ),
        migrations.RenameField(
            model_name='tbencabfacvta',
            old_name='nid_cliente',
            new_name='nidCliente',
        ),
        migrations.AlterField(
            model_name='carrito',
            name='fecha_creacion',
            field=models.DateField(blank=True, default='2024-11-29', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='tbdetfactvta',
            unique_together={('idFact', 'idProducto')},
        ),
    ]
