# Generated by Django 3.2 on 2024-11-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0015_auto_20241130_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbdetfactvta',
            name='valVenta',
        ),
        migrations.AddField(
            model_name='tbdetfactvta',
            name='val_venta',
            field=models.FloatField(default=0.0),
        ),
    ]
