# Generated by Django 3.2 on 2024-11-30 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0016_auto_20241130_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbdetfactvta',
            name='id',
        ),
        migrations.AlterField(
            model_name='tbdetfactvta',
            name='idFact',
            field=models.ForeignKey(db_column='idFact', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='appVeterinaria.tbencabfacvta'),
        ),
    ]
